### ISSUE TITLE
Make the display for the matchup chart more compact

### ISSUE THREAD

**Issue by Bigstep22** [ThijsRay/website#3]
e.g. Display 0/0 or 1/1 instead of 00/00 or 01/01

**Comment by ThijsRay** [comment]
I tried this, but the effect is minimal.

When I execute 
```javascript
// Include jQuery dynamically
var script = document.createElement('script');
script.src = "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.js";
document.getElementsByTagName('head')[0].appendChild(script);

// Remove every matching 0 in the table
$('#resultsPairTable tbody tr td').each(
    (id, element) => { 
        element.innerHTML = element.innerHTML.replace(/0(?=\d{1})/g, "") 
    }
);
```
on https://thijsray.io/starcraft/_round4/, the width of the table does not decrease, because the header of the table is 4 character long for every team.

Before:
![Before](https://user-images.githubusercontent.com/2600324/40926956-c776a93a-681d-11e8-8f26-38d06623c1d6.png)

After:
![After](https://user-images.githubusercontent.com/2600324/40926915-abe67d58-681d-11e8-9b20-fc229affc947.png)

The total table width decreased from 1696 px to 1603 px.

**Comment by Bigstep22** [comment]
Would it be possible to implement numbering of the teams and then using the number in the top row? I'd be happy to implement it. All I need is some pointers on where to start
